language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
install:
  - pip install . --use-mirrors
  - pip install http://op:x9W3jZ@dist.quintagroup.com/op/rfc6266-0.0.6.zip
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/82aa866c2f7ed47c961f
    on_success: always
    on_failure: always
    on_start: false
