language: python
python:
  - "2.7"
services:
  - couchdb
before_install:
  - easy_install -U setuptools
install:
  - pip install . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - nosetests
after_success:
  - coveralls
